services:
  backend:
    build: ./backend
    ports:
    - "3000:3000"
    environment:
      - JWT_SECRET=uma_chave_super_secreta_e_longa_123
    volumes:
      - ./backend:/app
      - /app/node_modules


  frontend:
    build: ./frontend
    ports:
    - "80:80"
    depends_on:
    - backend